- name: generate new HAPEE LB configuration
  template:
    src: hapee-lb.cfg.j2
    dest: /etc/hapee-1.8/hapee-lb.cfg
    mode: 0664
    owner: root
    group: hapee

- name: restart HAPEE LB service
  systemd:
    name: hapee-1.8-lb
    state: restarted